export { default as cervezaLogo } from "./cervezaLogo.png"
export { default as imgFacebookLogo } from "./facebookLogo.png" 
export { default as imgInstagramLogo } from "./instagramLogo.png" 
export { default as imgBarLogo } from "./logoBar.jpg"
export { default as imgNavBar } from "./restaurant.jpg"
export { default as bar1 } from "./1.jpg"
export { default as bar2 } from "./2.jpg"
export { default as bar3 } from "./3.jpg"
export { default as bar4 } from "./4.jpg"
export { default as bar5 } from "./5.jpg"
export { default as bar6 } from "./6.jpg"
export { default as bar7 } from "./7.jpg"
export { default as bar8 } from "./8.jpg"
export { default as bar9 } from "./9.jpg"
export { default as bar10 } from "./10.jpg"
export { default as bar11 } from "./11.jpg"


